DROP TABLE IF EXISTS reviews CASCADE;
CREATE TABLE reviews(
    id SERIAL PRIMARY KEY NOT NULL,
    rating INTEGER NOT NULL,
    description VARCHAR(255) NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    car_id INTEGER REFERENCES cars(id) ON DELETE CASCADE
);
