DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE reviews(
    id SERIAL PRIMARY KEY NOT NULL,
    rating INTEGER NOT NULL,
    description VARCHAR(255) NOT NULL,
    user_id INTEGER REFERENCES user(id) ON DELETE CASCADE,
    car_id INTEGER REFERENCES cars(id) ON DELETE CASCADE
);
