INSERT INTO
cars(city_mpg, class, combination_mpg, cylinders, displacement, drive, fuel_type, highway_mpg, make, model, transmission, year, photo_URL)
VALUES
   (29, 
   'midsize car',
    32,
    4,
    1.8,
    'fwd',
    'gas',
    37,
    'toyota',
    'corolla',
    'a',
    2015,
    'https://www.carimagery.com/img/v2/5824.jpg'),
    
    (25,
    'midsize car',
    28,
    4,
    2.5,
    'fwd',
    'gas',
    34,
    'toyota',
    'camry',
    'a',
    2015,
    'https://www.carimagery.com/img/v2/12465.jpg')