INSERT INTO 
cars(city_mpg, class, combination_mpg, cylinders, displacement, drive, fuel_type, highway_mpg, make, model, transmission, year, photo_URL)
VALUES

(	null,	null,	null,	null,	null,	null,	null,	null,'Acura','ILX',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Acura','MDX',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Acura','NSX',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Acura','RDX',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Acura','TLX',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Alfa Romeo','Giulia',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Alfa Romeo','Stelvio',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Aston Martin','DB11',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Aston Martin','DBS',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Aston Martin','DBX',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Aston Martin','Vantage',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','A3',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','A4',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','A4 allroad',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','A5',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','A6',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','A6 allroad',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','A7',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','A8',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','e-tron',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','e-tron GT',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','e-tron S',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','e-tron S Sportback',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','e-tron Sportback',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','Q3',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','Q4 e-tron',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','Q4 Sportback e-tron',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','Q5',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','Q5 Sportback',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','Q7',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','Q8',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','R8',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','RS 3',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','RS 5',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','RS 6',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','RS 7',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','RS e-tron GT',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','RS Q8',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','S3',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','S4',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','S5',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','S6',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','S7',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','S8',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','SQ5',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','SQ5 Sportback',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','SQ7',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','SQ8',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Audi','TT',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Bentley','Bentayga',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Bentley','Continental GT',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Bentley','Flying Spur',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','2 Series',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','3 Series',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','4 Series',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','5 Series',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','7 Series',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','8 Series',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','i4',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','iX',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','M3',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','M4',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','M5',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','M8',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','X1',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','X2',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','X3',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','X3 M',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','X4',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','X4 M',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','X5',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','X5 M',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','X6',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','X6 M',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','X7',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'BMW','Z4',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Buick','Enclave',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Buick','Encore',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Buick','Encore GX',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Buick','Envision',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Cadillac','CT4',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Cadillac','CT5',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Cadillac','Escalade',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Cadillac','Escalade ESV',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Cadillac','XT4',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Cadillac','XT5',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Cadillac','XT6',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Blazer',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Bolt EUV',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Bolt EV',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Camaro',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Colorado Crew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Colorado Extended Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Corvette',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Equinox',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Express 2500 Cargo',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Express 2500 Passenger',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Express 3500 Cargo',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Express 3500 Passenger',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Malibu',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Silverado 1500 Crew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Silverado 1500 Double Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Silverado 1500 Limited Crew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Silverado 1500 Limited Double Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Silverado 1500 Limited Regular Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Silverado 1500 Regular Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Silverado 2500 HD Crew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Silverado 2500 HD Double Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Silverado 2500 HD Regular Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Silverado 3500 HD Crew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Silverado 3500 HD Double Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Silverado 3500 HD Regular Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Spark',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Suburban',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Tahoe',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Trailblazer',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Traverse',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chevrolet','Trax',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chrysler','300',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chrysler','Pacifica',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chrysler','Pacifica Hybrid',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Chrysler','Voyager',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Dodge','Challenger',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Dodge','Charger',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Dodge','Durango',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ferrari','296 GTB',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ferrari','812 Competizione',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ferrari','812 Competizione A',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ferrari','812 GTS',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ferrari','F8',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ferrari','Portofino',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ferrari','Roma',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ferrari','SF90',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'FIAT','500X',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Bronco',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Bronco Sport',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','EcoSport',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Edge',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Escape',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Escape Plug-in Hybrid',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','E-Transit 350 Cargo Van',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Expedition',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Expedition MAX',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Explorer',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','F150 Lightning',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','F150 Regular Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','F150 Super Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','F150 SuperCrew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','F250 Super Duty Crew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','F250 Super Duty Regular Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','F250 Super Duty Super Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','F350 Super Duty Crew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','F350 Super Duty Regular Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','F350 Super Duty Super Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','F450 Super Duty Crew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','F450 Super Duty Regular Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Maverick',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Mustang',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Mustang MACH-E',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Ranger SuperCab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Ranger SuperCrew',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Transit 150 Cargo Van',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Transit 150 Crew Van',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Transit 150 Passenger Van',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Transit 250 Cargo Van',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Transit 250 Crew Van',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Transit 350 Cargo Van',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Transit 350 Crew Van',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Transit 350 HD Cargo Van',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Transit 350 HD Crew Van',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Transit 350 Passenger Van',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Transit Connect Cargo Van',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ford','Transit Connect Passenger Wagon',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Genesis','Electrified G80',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Genesis','G70',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Genesis','G80',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Genesis','G90',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Genesis','GV60',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Genesis','GV70',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Genesis','GV80',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Acadia',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Canyon Crew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Canyon Extended Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Hummer EV Pickup',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Savana 2500 Cargo',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Savana 2500 Passenger',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Savana 3500 Cargo',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Savana 3500 Passenger',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Sierra 1500 Crew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Sierra 1500 Double Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Sierra 1500 Limited Crew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Sierra 1500 Limited Double Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Sierra 1500 Limited Regular Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Sierra 1500 Regular Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Sierra 2500 HD Crew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Sierra 2500 HD Double Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Sierra 2500 HD Regular Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Sierra 3500 HD Crew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Sierra 3500 HD Double Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Sierra 3500 HD Regular Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Terrain',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Yukon',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'GMC','Yukon XL',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Honda','Accord',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Honda','Accord Hybrid',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Honda','Civic',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Honda','Civic Type R',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Honda','CR-V',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Honda','CR-V Hybrid',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Honda','HR-V',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Honda','Insight',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Honda','Odyssey',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Honda','Passport',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Honda','Pilot',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Honda','Ridgeline',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','Accent',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','Elantra',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','Elantra N',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','IONIQ 5',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','Ioniq Hybrid',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','Ioniq Plug-in Hybrid',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','Kona',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','Kona Electric',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','Kona N',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','NEXO',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','Palisade',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','Santa Cruz',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','Santa Fe',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','Santa Fe Hybrid',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','Santa Fe Plug-in Hybrid',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','Sonata',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','Sonata Hybrid',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','Tucson',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','Tucson Hybrid',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','Tucson Plug-in Hybrid',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','Veloster',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Hyundai','Venue',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'INFINITI','Q50',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'INFINITI','Q60',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'INFINITI','QX50',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'INFINITI','QX55',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'INFINITI','QX60',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'INFINITI','QX80',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Jaguar','E-PACE',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Jaguar','F-PACE',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Jaguar','F-TYPE',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Jaguar','I-PACE',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Jaguar','XF',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Jeep','Cherokee',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Jeep','Compass',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Jeep','Gladiator',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Jeep','Grand Cherokee',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Jeep','Grand Cherokee 4xe',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Jeep','Grand Cherokee L',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Jeep','Grand Wagoneer',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Jeep','Renegade',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Jeep','Wagoneer',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Jeep','Wrangler',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Jeep','Wrangler Unlimited',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Jeep','Wrangler Unlimited 4xe',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Kia','Carnival',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Kia','EV6',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Kia','Forte',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Kia','K5',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Kia','Niro',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Kia','Niro EV',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Kia','Niro Plug-in Hybrid',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Kia','Rio',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Kia','Seltos',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Kia','Sorento',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Kia','Sorento Hybrid',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Kia','Sorento Plug-in Hybrid',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Kia','Soul',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Kia','Sportage',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Kia','Stinger',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Kia','Telluride',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Lamborghini','Aventador',	null,	2015	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Lamborghini','Huracan',	null,	2015	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Lamborghini','Urus',	null,	2019	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Land Rover','Defender 110',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Land Rover','Defender 90',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Land Rover','Discovery',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Land Rover','Discovery Sport',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Land Rover','Range Rover',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Land Rover','Range Rover Evoque',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Land Rover','Range Rover Sport',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Land Rover','Range Rover Velar',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Lexus','ES',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Lexus','GX',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Lexus','IS',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Lexus','LC',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Lexus','LS',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Lexus','LX',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Lexus','NX',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Lexus','RC',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Lexus','RX',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Lexus','UX',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Lincoln','Aviator',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Lincoln','Corsair',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Lincoln','Nautilus',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Lincoln','Navigator',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Lincoln','Navigator L',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Lucid','Air',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Maserati','Ghibli',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Maserati','Levante',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Maserati','MC20',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Maserati','Quattroporte',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'MAZDA','CX-30',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'MAZDA','CX-5',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'MAZDA','CX-9',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'MAZDA','MAZDA3',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'MAZDA','MX-30',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'MAZDA','MX-5 Miata',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'MAZDA','MX-5 Miata RF',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','A-Class',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','C-Class',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','CLA',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','CLS',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','E-Class',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','G-Class',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','GLA',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','GLB',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','GLC',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','GLC Coupe',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','GLE',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','GLS',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Mercedes-AMG C-Class',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Mercedes-AMG CLA',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Mercedes-AMG E-Class',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Mercedes-AMG EQS',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Mercedes-AMG GLA',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Mercedes-AMG GLB',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Mercedes-AMG GLC',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Mercedes-AMG GLC Coupe',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Mercedes-AMG GLE',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Mercedes-AMG GLE Coupe',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Mercedes-AMG GLS',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Mercedes-AMG GT',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Mercedes-AMG SL',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Mercedes-EQ EQB',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Mercedes-EQ EQS',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Mercedes-Maybach GLS',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Mercedes-Maybach S-Class',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Metris Cargo',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Metris Passenger',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','S-Class',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Sprinter 1500 Cargo',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Sprinter 1500 Passenger',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Sprinter 2500 Cargo',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Sprinter 2500 Crew',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Sprinter 2500 Passenger',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Sprinter 3500 Cargo',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Sprinter 3500 Crew',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Sprinter 3500 XD Cargo',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Sprinter 3500 XD Crew',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Sprinter 4500 Cargo',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mercedes-Benz','Sprinter 4500 Crew',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'MINI','Clubman',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'MINI','Convertible',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'MINI','Countryman',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'MINI','Hardtop 2 Door',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'MINI','Hardtop 4 Door',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mitsubishi','Eclipse Cross',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mitsubishi','Mirage',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mitsubishi','Mirage G4',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mitsubishi','Outlander',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mitsubishi','Outlander PHEV',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Mitsubishi','Outlander Sport',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Nissan','400Z',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Nissan','Altima',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Nissan','Armada',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Nissan','Frontier Crew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Nissan','Frontier King Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Nissan','Kicks',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Nissan','LEAF',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Nissan','Maxima',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Nissan','Murano',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Nissan','Pathfinder',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Nissan','Rogue',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Nissan','Rogue Sport',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Nissan','Sentra',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Nissan','Titan Crew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Nissan','Titan King Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Nissan','TITAN XD Crew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Nissan','Versa',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Polestar','2',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Porsche','718 Boxster',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Porsche','718 Cayman',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Porsche','718 Spyder',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Porsche','911',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Porsche','Cayenne',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Porsche','Cayenne Coupe',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Porsche','Macan',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Porsche','Panamera',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Porsche','Taycan',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Porsche','Taycan Cross Turismo',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ram','1500 Classic Crew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ram','1500 Classic Quad Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ram','1500 Classic Regular Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ram','1500 Crew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ram','1500 Quad Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ram','2500 Crew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ram','2500 Mega Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ram','2500 Regular Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ram','3500 Crew Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ram','3500 Mega Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ram','3500 Regular Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ram','ProMaster Cargo Van',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ram','ProMaster City',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Ram','ProMaster Window Van',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Rivian','R1S',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Rivian','R1T',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Rolls-Royce','Cullinan',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Rolls-Royce','Ghost',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Rolls-Royce','Phantom',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Subaru','Ascent',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Subaru','BRZ',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Subaru','Crosstrek',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Subaru','Forester',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Subaru','Impreza',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Subaru','Legacy',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Subaru','Outback',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Subaru','WRX',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Tesla','Cybertruck',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Tesla','Model 3',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Tesla','Model S',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Tesla','Model X',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Tesla','Model Y',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','4Runner',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','86',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Avalon',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Avalon Hybrid',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Camry',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Camry Hybrid',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','C-HR',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Corolla',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Corolla Cross',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Corolla Hatchback',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Corolla Hybrid',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','GR Supra',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','GR86',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Highlander',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Highlander Hybrid',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Mirai',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Prius',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Prius Prime',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','RAV4',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','RAV4 Hybrid',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','RAV4 Prime',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Sequoia',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Sienna',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Tacoma Access Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Tacoma Double Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Tundra CrewMax',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Tundra Double Cab',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Tundra Hybrid CrewMax',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Toyota','Venza',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Volkswagen','Arteon',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Volkswagen','Atlas',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Volkswagen','Atlas Cross Sport',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Volkswagen','Golf GTI',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Volkswagen','Golf R',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Volkswagen','ID.4',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Volkswagen','Jetta',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Volkswagen','Jetta GLI',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Volkswagen','Passat',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Volkswagen','Taos',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Volkswagen','Tiguan',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Volvo','C40 Recharge',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Volvo','S60',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Volvo','S90',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Volvo','V60',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Volvo','V90',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Volvo','XC40',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Volvo','XC40 Recharge',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Volvo','XC60',	null,	2022	,	null	)	,
(	null,	null,	null,	null,	null,	null,	null,	null,'Volvo','XC90',	null,	2022	,	null	)	

