INSERT INTO cars_lists(make, model)
VALUES

('Acura','ILX'),
('Acura','MDX'),
('Acura','NSX'),
('Acura','RDX'),
('Acura','TLX'),
('Alfa Romeo','Giulia'),
('Alfa Romeo','Stelvio'),
('Aston Martin','DB11'),
('Aston Martin','DBS'),
('Aston Martin','DBX'),
('Aston Martin','Vantage'),
('Audi','A3'),
('Audi','A4'),
('Audi','A4 allroad'),
('Audi','A5'),
('Audi','A6'),
('Audi','A6 allroad'),
('Audi','A7'),
('Audi','A8'),
('Audi','e-tron'),
('Audi','e-tron GT'),
('Audi','e-tron S'),
('Audi','e-tron S Sportback'),
('Audi','e-tron Sportback'),
('Audi','Q3'),
('Audi','Q4 e-tron'),
('Audi','Q4 Sportback e-tron'),
('Audi','Q5'),
('Audi','Q5 Sportback'),
('Audi','Q7'),
('Audi','Q8'),
('Audi','R8'),
('Audi','RS 3'),
('Audi','RS 5'),
('Audi','RS 6'),
('Audi','RS 7'),
('Audi','RS e-tron GT'),
('Audi','RS Q8'),
('Audi','S3'),
('Audi','S4'),
('Audi','S5'),
('Audi','S6'),
('Audi','S7'),
('Audi','S8'),
('Audi','SQ5'),
('Audi','SQ5 Sportback'),
('Audi','SQ7'),
('Audi','SQ8'),
('Audi','TT'),
('Bentley','Bentayga'),
('Bentley','Continental GT'),
('Bentley','Flying Spur'),
('BMW','2 Series'),
('BMW','3 Series'),
('BMW','4 Series'),
('BMW','5 Series'),
('BMW','7 Series'),
('BMW','8 Series'),
('BMW','i4'),
('BMW','iX'),
('BMW','M3'),
('BMW','M4'),
('BMW','M5'),
('BMW','M8'),
('BMW','X1'),
('BMW','X2'),
('BMW','X3'),
('BMW','X3 M'),
('BMW','X4'),
('BMW','X4 M'),
('BMW','X5'),
('BMW','X5 M'),
('BMW','X6'),
('BMW','X6 M'),
('BMW','X7'),
('BMW','Z4'),
('Buick','Enclave'),
('Buick','Encore'),
('Buick','Encore GX'),
('Buick','Envision'),
('Cadillac','CT4'),
('Cadillac','CT5'),
('Cadillac','Escalade'),
('Cadillac','Escalade ESV'),
('Cadillac','XT4'),
('Cadillac','XT5'),
('Cadillac','XT6'),
('Chevrolet','Blazer'),
('Chevrolet','Bolt EUV'),
('Chevrolet','Bolt EV'),
('Chevrolet','Camaro'),
('Chevrolet','Colorado Crew Cab'),
('Chevrolet','Colorado Extended Cab'),
('Chevrolet','Corvette'),
('Chevrolet','Equinox'),
('Chevrolet','Express 2500 Cargo'),
('Chevrolet','Express 2500 Passenger'),
('Chevrolet','Express 3500 Cargo'),
('Chevrolet','Express 3500 Passenger'),
('Chevrolet','Malibu'),
('Chevrolet','Silverado 1500 Crew Cab'),
('Chevrolet','Silverado 1500 Double Cab'),
('Chevrolet','Silverado 1500 Limited Crew Cab'),
('Chevrolet','Silverado 1500 Limited Double Cab'),
('Chevrolet','Silverado 1500 Limited Regular Cab'),
('Chevrolet','Silverado 1500 Regular Cab'),
('Chevrolet','Silverado 2500 HD Crew Cab'),
('Chevrolet','Silverado 2500 HD Double Cab'),
('Chevrolet','Silverado 2500 HD Regular Cab'),
('Chevrolet','Silverado 3500 HD Crew Cab'),
('Chevrolet','Silverado 3500 HD Double Cab'),
('Chevrolet','Silverado 3500 HD Regular Cab'),
('Chevrolet','Spark'),
('Chevrolet','Suburban'),
('Chevrolet','Tahoe'),
('Chevrolet','Trailblazer'),
('Chevrolet','Traverse'),
('Chevrolet','Trax'),
('Chrysler','300'),
('Chrysler','Pacifica'),
('Chrysler','Pacifica Hybrid'),
('Chrysler','Voyager'),
('Dodge','Challenger'),
('Dodge','Charger'),
('Dodge','Durango'),
('Ferrari','296 GTB'),
('Ferrari','812 Competizione'),
('Ferrari','812 Competizione A'),
('Ferrari','812 GTS'),
('Ferrari','F8'),
('Ferrari','Portofino'),
('Ferrari','Roma'),
('Ferrari','SF90'),
('FIAT','500X'),
('Ford','Bronco'),
('Ford','Bronco Sport'),
('Ford','EcoSport'),
('Ford','Edge'),
('Ford','Escape'),
('Ford','Escape Plug-in Hybrid'),
('Ford','E-Transit 350 Cargo Van'),
('Ford','Expedition'),
('Ford','Expedition MAX'),
('Ford','Explorer'),
('Ford','F150 Lightning'),
('Ford','F150 Regular Cab'),
('Ford','F150 Super Cab'),
('Ford','F150 SuperCrew Cab'),
('Ford','F250 Super Duty Crew Cab'),
('Ford','F250 Super Duty Regular Cab'),
('Ford','F250 Super Duty Super Cab'),
('Ford','F350 Super Duty Crew Cab'),
('Ford','F350 Super Duty Regular Cab'),
('Ford','F350 Super Duty Super Cab'),
('Ford','F450 Super Duty Crew Cab'),
('Ford','F450 Super Duty Regular Cab'),
('Ford','Maverick'),
('Ford','Mustang'),
('Ford','Mustang MACH-E'),
('Ford','Ranger SuperCab'),
('Ford','Ranger SuperCrew'),
('Ford','Transit 150 Cargo Van'),
('Ford','Transit 150 Crew Van'),
('Ford','Transit 150 Passenger Van'),
('Ford','Transit 250 Cargo Van'),
('Ford','Transit 250 Crew Van'),
('Ford','Transit 350 Cargo Van'),
('Ford','Transit 350 Crew Van'),
('Ford','Transit 350 HD Cargo Van'),
('Ford','Transit 350 HD Crew Van'),
('Ford','Transit 350 Passenger Van'),
('Ford','Transit Connect Cargo Van'),
('Ford','Transit Connect Passenger Wagon'),
('Genesis','Electrified G80'),
('Genesis','G70'),
('Genesis','G80'),
('Genesis','G90'),
('Genesis','GV60'),
('Genesis','GV70'),
('Genesis','GV80'),
('GMC','Acadia'),
('GMC','Canyon Crew Cab'),
('GMC','Canyon Extended Cab'),
('GMC','Hummer EV Pickup'),
('GMC','Savana 2500 Cargo'),
('GMC','Savana 2500 Passenger'),
('GMC','Savana 3500 Cargo'),
('GMC','Savana 3500 Passenger'),
('GMC','Sierra 1500 Crew Cab'),
('GMC','Sierra 1500 Double Cab'),
('GMC','Sierra 1500 Limited Crew Cab'),
('GMC','Sierra 1500 Limited Double Cab'),
('GMC','Sierra 1500 Limited Regular Cab'),
('GMC','Sierra 1500 Regular Cab'),
('GMC','Sierra 2500 HD Crew Cab'),
('GMC','Sierra 2500 HD Double Cab'),
('GMC','Sierra 2500 HD Regular Cab'),
('GMC','Sierra 3500 HD Crew Cab'),
('GMC','Sierra 3500 HD Double Cab'),
('GMC','Sierra 3500 HD Regular Cab'),
('GMC','Terrain'),
('GMC','Yukon'),
('GMC','Yukon XL'),
('Honda','Accord'),
('Honda','Accord Hybrid'),
('Honda','Civic'),
('Honda','Civic Type R'),
('Honda','CR-V'),
('Honda','CR-V Hybrid'),
('Honda','HR-V'),
('Honda','Insight'),
('Honda','Odyssey'),
('Honda','Passport'),
('Honda','Pilot'),
('Honda','Ridgeline'),
('Hyundai','Accent'),
('Hyundai','Elantra'),
('Hyundai','Elantra N'),
('Hyundai','IONIQ 5'),
('Hyundai','Ioniq Hybrid'),
('Hyundai','Ioniq Plug-in Hybrid'),
('Hyundai','Kona'),
('Hyundai','Kona Electric'),
('Hyundai','Kona N'),
('Hyundai','NEXO'),
('Hyundai','Palisade'),
('Hyundai','Santa Cruz'),
('Hyundai','Santa Fe'),
('Hyundai','Santa Fe Hybrid'),
('Hyundai','Santa Fe Plug-in Hybrid'),
('Hyundai','Sonata'),
('Hyundai','Sonata Hybrid'),
('Hyundai','Tucson'),
('Hyundai','Tucson Hybrid'),
('Hyundai','Tucson Plug-in Hybrid'),
('Hyundai','Veloster'),
('Hyundai','Venue'),
('INFINITI','Q50'),
('INFINITI','Q60'),
('INFINITI','QX50'),
('INFINITI','QX55'),
('INFINITI','QX60'),
('INFINITI','QX80'),
('Jaguar','E-PACE'),
('Jaguar','F-PACE'),
('Jaguar','F-TYPE'),
('Jaguar','I-PACE'),
('Jaguar','XF'),
('Jeep','Cherokee'),
('Jeep','Compass'),
('Jeep','Gladiator'),
('Jeep','Grand Cherokee'),
('Jeep','Grand Cherokee 4xe'),
('Jeep','Grand Cherokee L'),
('Jeep','Grand Wagoneer'),
('Jeep','Renegade'),
('Jeep','Wagoneer'),
('Jeep','Wrangler'),
('Jeep','Wrangler Unlimited'),
('Jeep','Wrangler Unlimited 4xe'),
('Kia','Carnival'),
('Kia','EV6'),
('Kia','Forte'),
('Kia','K5'),
('Kia','Niro'),
('Kia','Niro EV'),
('Kia','Niro Plug-in Hybrid'),
('Kia','Rio'),
('Kia','Seltos'),
('Kia','Sorento'),
('Kia','Sorento Hybrid'),
('Kia','Sorento Plug-in Hybrid'),
('Kia','Soul'),
('Kia','Sportage'),
('Kia','Stinger'),
('Kia','Telluride'),
('Lamborghini','Aventador'),
('Lamborghini','Huracan'),
('Lamborghini','Urus'),
('Land Rover','Defender 110'),
('Land Rover','Defender 90'),
('Land Rover','Discovery'),
('Land Rover','Discovery Sport'),
('Land Rover','Range Rover'),
('Land Rover','Range Rover Evoque'),
('Land Rover','Range Rover Sport'),
('Land Rover','Range Rover Velar'),
('Lexus','ES'),
('Lexus','GX'),
('Lexus','IS'),
('Lexus','LC'),
('Lexus','LS'),
('Lexus','LX'),
('Lexus','NX'),
('Lexus','RC'),
('Lexus','RX'),
('Lexus','UX'),
('Lincoln','Aviator'),
('Lincoln','Corsair'),
('Lincoln','Nautilus'),
('Lincoln','Navigator'),
('Lincoln','Navigator L'),
('Lucid','Air'),
('Maserati','Ghibli'),
('Maserati','Levante'),
('Maserati','MC20'),
('Maserati','Quattroporte'),
('MAZDA','CX-30'),
('MAZDA','CX-5'),
('MAZDA','CX-9'),
('MAZDA','MAZDA3'),
('MAZDA','MX-30'),
('MAZDA','MX-5 Miata'),
('MAZDA','MX-5 Miata RF'),
('Mercedes-Benz','A-Class'),
('Mercedes-Benz','C-Class'),
('Mercedes-Benz','CLA'),
('Mercedes-Benz','CLS'),
('Mercedes-Benz','E-Class'),
('Mercedes-Benz','G-Class'),
('Mercedes-Benz','GLA'),
('Mercedes-Benz','GLB'),
('Mercedes-Benz','GLC'),
('Mercedes-Benz','GLC Coupe'),
('Mercedes-Benz','GLE'),
('Mercedes-Benz','GLS'),
('Mercedes-Benz','Mercedes-AMG C-Class'),
('Mercedes-Benz','Mercedes-AMG CLA'),
('Mercedes-Benz','Mercedes-AMG E-Class'),
('Mercedes-Benz','Mercedes-AMG EQS'),
('Mercedes-Benz','Mercedes-AMG GLA'),
('Mercedes-Benz','Mercedes-AMG GLB'),
('Mercedes-Benz','Mercedes-AMG GLC'),
('Mercedes-Benz','Mercedes-AMG GLC Coupe'),
('Mercedes-Benz','Mercedes-AMG GLE'),
('Mercedes-Benz','Mercedes-AMG GLE Coupe'),
('Mercedes-Benz','Mercedes-AMG GLS'),
('Mercedes-Benz','Mercedes-AMG GT'),
('Mercedes-Benz','Mercedes-AMG SL'),
('Mercedes-Benz','Mercedes-EQ EQB'),
('Mercedes-Benz','Mercedes-EQ EQS'),
('Mercedes-Benz','Mercedes-Maybach GLS'),
('Mercedes-Benz','Mercedes-Maybach S-Class'),
('Mercedes-Benz','Metris Cargo'),
('Mercedes-Benz','Metris Passenger'),
('Mercedes-Benz','S-Class'),
('Mercedes-Benz','Sprinter 1500 Cargo'),
('Mercedes-Benz','Sprinter 1500 Passenger'),
('Mercedes-Benz','Sprinter 2500 Cargo'),
('Mercedes-Benz','Sprinter 2500 Crew'),
('Mercedes-Benz','Sprinter 2500 Passenger'),
('Mercedes-Benz','Sprinter 3500 Cargo'),
('Mercedes-Benz','Sprinter 3500 Crew'),
('Mercedes-Benz','Sprinter 3500 XD Cargo'),
('Mercedes-Benz','Sprinter 3500 XD Crew'),
('Mercedes-Benz','Sprinter 4500 Cargo'),
('Mercedes-Benz','Sprinter 4500 Crew'),
('MINI','Clubman'),
('MINI','Convertible'),
('MINI','Countryman'),
('MINI','Hardtop 2 Door'),
('MINI','Hardtop 4 Door'),
('Mitsubishi','Eclipse Cross'),
('Mitsubishi','Mirage'),
('Mitsubishi','Mirage G4'),
('Mitsubishi','Outlander'),
('Mitsubishi','Outlander PHEV'),
('Mitsubishi','Outlander Sport'),
('Nissan','400Z'),
('Nissan','Altima'),
('Nissan','Armada'),
('Nissan','Frontier Crew Cab'),
('Nissan','Frontier King Cab'),
('Nissan','Kicks'),
('Nissan','LEAF'),
('Nissan','Maxima'),
('Nissan','Murano'),
('Nissan','Pathfinder'),
('Nissan','Rogue'),
('Nissan','Rogue Sport'),
('Nissan','Sentra'),
('Nissan','Titan Crew Cab'),
('Nissan','Titan King Cab'),
('Nissan','TITAN XD Crew Cab'),
('Nissan','Versa'),
('Polestar','2'),
('Porsche','718 Boxster'),
('Porsche','718 Cayman'),
('Porsche','718 Spyder'),
('Porsche','911'),
('Porsche','Cayenne'),
('Porsche','Cayenne Coupe'),
('Porsche','Macan'),
('Porsche','Panamera'),
('Porsche','Taycan'),
('Porsche','Taycan Cross Turismo'),
('Ram','1500 Classic Crew Cab'),
('Ram','1500 Classic Quad Cab'),
('Ram','1500 Classic Regular Cab'),
('Ram','1500 Crew Cab'),
('Ram','1500 Quad Cab'),
('Ram','2500 Crew Cab'),
('Ram','2500 Mega Cab'),
('Ram','2500 Regular Cab'),
('Ram','3500 Crew Cab'),
('Ram','3500 Mega Cab'),
('Ram','3500 Regular Cab'),
('Ram','ProMaster Cargo Van'),
('Ram','ProMaster City'),
('Ram','ProMaster Window Van'),
('Rivian','R1S'),
('Rivian','R1T'),
('Rolls-Royce','Cullinan'),
('Rolls-Royce','Ghost'),
('Rolls-Royce','Phantom'),
('Subaru','Ascent'),
('Subaru','BRZ'),
('Subaru','Crosstrek'),
('Subaru','Forester'),
('Subaru','Impreza'),
('Subaru','Legacy'),
('Subaru','Outback'),
('Subaru','WRX'),
('Tesla','Cybertruck'),
('Tesla','Model 3'),
('Tesla','Model S'),
('Tesla','Model X'),
('Tesla','Model Y'),
('Toyota','4Runner'),
('Toyota','86'),
('Toyota','Avalon'),
('Toyota','Avalon Hybrid'),
('Toyota','Camry'),
('Toyota','Camry Hybrid'),
('Toyota','C-HR'),
('Toyota','Corolla'),
('Toyota','Corolla Cross'),
('Toyota','Corolla Hatchback'),
('Toyota','Corolla Hybrid'),
('Toyota','GR Supra'),
('Toyota','GR86'),
('Toyota','Highlander'),
('Toyota','Highlander Hybrid'),
('Toyota','Mirai'),
('Toyota','Prius'),
('Toyota','Prius Prime'),
('Toyota','RAV4'),
('Toyota','RAV4 Hybrid'),
('Toyota','RAV4 Prime'),
('Toyota','Sequoia'),
('Toyota','Sienna'),
('Toyota','Tacoma Access Cab'),
('Toyota','Tacoma Double Cab'),
('Toyota','Tundra CrewMax'),
('Toyota','Tundra Double Cab'),
('Toyota','Tundra Hybrid CrewMax'),
('Toyota','Venza'),
('Volkswagen','Arteon'),
('Volkswagen','Atlas'),
('Volkswagen','Atlas Cross Sport'),
('Volkswagen','Golf GTI'),
('Volkswagen','Golf R'),
('Volkswagen','ID.4'),
('Volkswagen','Jetta'),
('Volkswagen','Jetta GLI'),
('Volkswagen','Passat'),
('Volkswagen','Taos'),
('Volkswagen','Tiguan'),
('Volvo','C40 Recharge'),
('Volvo','S60'),
('Volvo','S90'),
('Volvo','V60'),
('Volvo','V90'),
('Volvo','XC40'),
('Volvo','XC40 Recharge'),
('Volvo','XC60'),
('Volvo','XC90')